#!/usr/bin/env bash
join_tokens () {
  local IFS=:
  echo "$*"
}
JARS=()
for JAR in build/libs/*.jar dependencies/*.jar; do
  JARS+=($JAR)
done
MODULE_PATH=`join_tokens ${JARS[@]}`
echo "$MODULE_PATH"
