#!/usr/bin/env bash
join_tokens () {
  local IFS=:
  echo "$*"
}
JARS=()
for JAR in `find build/libs -name "*.jar"`; do
  JARS+=($JAR)
done
MODULE_PATH=`join_tokens ${JARS[@]}`
rm -rf out
jpackage --name cp --type app-image --module-path $MODULE_PATH --module jbock.gradle.example/net.jbock.cp.CopyFile --dest out

# create launcher script
echo '#!/usr/bin/env bash' >cp
EXECUTABLE=`find out -type f -name cp`
echo "$EXECUTABLE" '$@' >>cp
chmod +x cp
