#!/usr/bin/env bash
MODULE_PATH=target/jbock-maven-example-0-SNAPSHOT.jar
for JAR in `find build/libs -name "*.jar"`; do
       MODULE_PATH="${MODULE_PATH}:${JAR}"
done
rm -rf out
jpackage --name cp --type app-image --module-path $MODULE_PATH --module jbock.gradle.example/net.jbock.cp.CopyFile --dest out

